### ISSUE TITLE
Integrate travis-ci File

### ISSUE THREAD

**Issue by ghermans** [idevelopment/serviceforce#1]

**Comment by Tjoosten** [comment]
@ghermans is the travisCI service activated for this repo?

**Comment by ghermans** [comment]
@Tjoosten I will check this right now

**Comment by ghermans** [comment]
@Tjoosten i just activated travis.

**Comment by Tjoosten** [comment]
@ghermans When u want the implementation. Today or tomorrow?

**Comment by ghermans** [comment]
Tomorrow is fine :)
