### ISSUE TITLE
Server Operating systems

### ISSUE THREAD

**Issue by ghermans** [idevelopment/serviceforce#26]
## TODO
- [x] retrieve a list of all of available Operating Systems from the API
- [x] Save them to the DB
## Migration

| Name | Type | Description |
| --- | --- | --- |
| id | integer | The identifier for the Operating Systems resource |
| name | string | The name of the Operating Systems resource |

**Comment by Tjoosten** [comment]
@ghermans reason for reopening?

**Comment by ghermans** [comment]
@Tjoosten check the comments on https://github.com/idevelopment/serviceforce/pull/38
