### ISSUE TITLE
Design error. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/serviceforce#28]
<img width="1235" alt="schermafbeelding 2016-05-30 om 22 34 11" src="https://cloud.githubusercontent.com/assets/5157609/15657969/b9016e1c-26b6-11e6-9779-66f3e392bc85.png">

**Comment by ghermans** [comment]
@Tjoosten  working on it atm

**Comment by Tjoosten** [comment]
@ghermans still not fixed i got the same view.
