### ISSUE TITLE
customer status is missing 

### ISSUE THREAD

**Issue by ghermans** [idevelopment/serviceforce#34]
## Customer status migration
- name
- description
- bgcolor
## Customer status seeder

| Value | Description | Background |
| --- | --- | --- |
| Active |  | success |
| Suspended | Suspended due billing or abuse issues | warning |
| Terminated | All services are terminated for this account | danger |

**Comment by Tjoosten** [comment]
Suspended and terminated are not in the database migration. Right @ghermans ?

**Comment by ghermans** [comment]
@Tjoosten  in the customers migration file we just need to add a status column.
the above data is a separated migration file.

**Comment by Tjoosten** [comment]
Alright

**Comment by Tjoosten** [comment]
@ghermans **IDEA:** What if we do this through bouncer?

**Comment by ghermans** [comment]
We can do that, keep in mind that when we change the status it will send api calls to plesk & suitecrm & LSW and openprovider.

**Comment by Tjoosten** [comment]
@ghermans DANM son
