### ISSUE TITLE
Add artisan command - save pay-as-you-go-instances to BaseServers table

### ISSUE THREAD

**Issue by ghermans** [idevelopment/serviceforce#42]
To retrieve a list of all Pay-as-you-go instances send a GET request to /v1/payAsYouGo/bareMetals/instances.

The response will be a JSON object with key instances containing purchased Pay-as-you-go servers with the following attributes:

| Name | Type | Description |
| --- | --- | --- |
| bareMetalId | string | The identifier of the Bare Metal resource |
| customerNumber | string | Your customer number |
| model | integer | The number of the model that you purchased |
| pricePerGb | number | Displays the price that is billed per Gb of traffic |
| pricePerHour | number | Displays the price that is billed per hour of instance usage |
| startedAt | string | String containing the time in which the instance started to run |
| destroyedAt | string | (Optional) If the instance is destroyed, shows the time in which was destroyed |

**Comment by Tjoosten** [comment]
https://github.com/idevelopment/serviceforce/commit/ca1e6877451e2323734e45d039cde3d9fcb553d6

**Comment by ghermans** [comment]
@Tjoosten any update on this?

**Comment by Tjoosten** [comment]
Since https://github.com/idevelopment/serviceforce/commit/ca1e6877451e2323734e45d039cde3d9fcb553d6 i did nothing on this

**Comment by ghermans** [comment]
@Tjoosten when do you push the new changes?
