### ISSUE TITLE
MySQL error after login. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/serviceforce#76]
<img width="1048" alt="schermafbeelding 2016-08-14 om 23 36 13" src="https://cloud.githubusercontent.com/assets/5157609/17652253/fd7ef30a-6277-11e6-96fe-7026039a8540.png">

**Comment by ghermans** [comment]
did you do the following after the git pull?
- composer dump-autoload
- artisan migrate:reset
- artisan migrate
- artisan db:seed

**Comment by Tjoosten** [comment]
Invalid.
